import { DVR, Camera, LogEntry, Alerta } from './types';

export const MOCK_DVRS: DVR[] = [
  {
    id: '1',
    name: 'Hikvision DS-7608NI-I2',
    ip: '192.168.1.42',
    location: 'PORTARIA',
    status: 'online',
    channels: 8,
    model: 'DS-7608NI-I2',
    firmware: 'v4.51.025_211224',
    user: 'admin_sys_01',
    hikConnect: true,
  },
  {
    id: '2',
    name: 'Hikvision DS-7204HQHI',
    ip: '10.0.0.15',
    location: 'ZELADOR',
    status: 'warning',
    channels: 4,
    model: 'DS-7204HQHI',
    firmware: 'v4.30.000_200512',
    user: 'admin_sys_02',
    hikConnect: true,
  },
  {
    id: '3',
    name: 'Hikvision DS-7616NI-K2',
    ip: '192.168.1.102',
    location: 'GARAGEM SUB-1',
    status: 'offline',
    channels: 16,
    model: 'DS-7616NI-K2',
    firmware: 'v4.40.015_201215',
    user: 'admin_sys_03',
    hikConnect: false,
  },
];

export const MOCK_CAMERAS: Camera[] = [
  {
    id: 'c1',
    name: 'Bloco A - Entrada Principal',
    ip: '192.168.1.104',
    location: 'Entrada Principal',
    status: 'online',
    type: 'IP',
    brand: 'HIKVISION',
    dvrId: '1',
    channel: 'CH-04',
    imageUrl: 'https://picsum.photos/seed/security1/800/450',
  },
  {
    id: 'c2',
    name: 'Estacionamento P1 - Sul',
    ip: 'SINAL OK',
    location: 'Estacionamento',
    status: 'online',
    type: 'ANALOG',
    brand: 'INTELBRAS',
    dvrId: '2',
    channel: 'CH-12',
    imageUrl: 'https://picsum.photos/seed/security2/800/450',
  },
  {
    id: 'c3',
    name: 'Data Center - Rack A3',
    ip: 'DESCONECTADA',
    location: 'Data Center',
    status: 'offline',
    type: 'IP',
    brand: 'JFL',
    dvrId: '1',
    channel: 'CH-32',
    imageUrl: 'https://picsum.photos/seed/security3/800/450',
  },
  {
    id: 'c4',
    name: 'Corredor B - Sala 104',
    ip: '192.168.1.105',
    location: 'Corredor B',
    status: 'online',
    type: 'ANALOG',
    brand: 'INTELBRAS',
    dvrId: '2',
    channel: 'CH-05',
  },
  {
    id: 'c5',
    name: 'Refeitório - Lateral',
    ip: '192.168.1.106',
    location: 'Refeitório',
    status: 'online',
    type: 'IP',
    brand: 'HIKVISION',
    dvrId: '1',
    channel: 'CH-14',
  },
];

export const MOCK_LOGS: LogEntry[] = [
  {
    id: 'l1',
    type: 'critical',
    message: 'Falha na Porta do Switch 04',
    location: 'Piso 2 Ala Norte',
    time: '16:22',
  },
  {
    id: 'l2',
    type: 'system',
    message: 'Backup do Sistema Concluído',
    location: 'Nó de Arquivo Cloud 01',
    time: '15:00',
  },
];

export const MOCK_ALERTAS: Alerta[] = [
  { id: 'a1', origin: 'CAM-WARE-02', event: 'Movimento Detectado', status: 'warning' },
  { id: 'a2', origin: 'PORTA-SEC-G1', event: 'Acesso Concedido', status: 'online' },
  { id: 'a3', origin: 'FOGO-LVL1-N', event: 'Teste Diag OK', status: 'system' },
];
